coslr: true
criterions:
  mixup:
    alpha: 0.8
endlr: 0.0
last: false
memory: {centroids: false, init_centroids: false}
model_dir: ./logs/ImageNet_LT/models/resnext50
networks:
  classifier:
    def_file: ./models/CosNormClassifier.py
    fix: true
    optim_params: {lr: 0.025, momentum: 0.9, weight_decay: 0.0005}
    params: {in_dims: 2048, out_dims: 1000, scale: 30}
  feat_model:
    def_file: ./models/ResNext50Feature_Ensemble.py
    fix: true
    optim_params: {lr: 0.025, momentum: 0.9, weight_decay: 0.0005}
    params: {dataset: ImageNet_LT, dropout: null,
      stage1_weights: false, use_fc: false, use_selfatt: false, num_classes: 1000, normalized: true, scale: 30}
shuffle: false
training_opt:
  backbone: resnext50
  batch_size: 128
  image_size: 224
  dataset: ImageNet_LT
  display_step: 200
  feature_dim: 2048
  log_dir: ./logs/ImageNet_LT/stage2/resnext50
  log_root: /logs/ImageNet_LT
  num_classes: 1000
  num_epochs: 200
  num_workers: 12
  open_threshold: 0.1
  sampler: null
  scheduler_params: {gamma: 0.1, step_size: 30}
  stage: resnext50
  sub_dir: stage2
  num_dir: ./data/ImageNet_LT/num_shots.npz
  bins: 4
  gamma: 2
  warmup_epoch: 5
  step1: 50
  step2: 70
  base_weight: 2
