coslr: true
criterions:
  mixup:
    alpha: 0.5
endlr: 0.0
last: false
model_dir: null
networks:
  feat_model:
    def_file: ./models/ViT_Ensemble_Create_Model.py
    fix: false
    optim_params: {lr: 0.000125, min_lr: 0.0000001, momentum: 0.9, weight_decay: 0.05, layer_decay: 0.75, adamW2: 0.99}
    params: {img_size: 384, patch_size: 16, num_classes: 365, drop_path: 0.1, global_pool: true,
            classifier_num: 3, normalized: true, aux_depth: 2, scale: 30, embed_dim: 768, depth: 12, num_heads: 12, 
            checkpoint: ./pretrain/ImageNet_1K_Res_384.pth}
shuffle: true
training_opt:
  backbone: ViTB_16_384
  batch_size: 32
  dataset: Places_LT
  image_size: 384
  display_step: 200
  feature_dim: 768
  log_dir: ./logs/Places_LT/models/ViTB_16_384
  log_root: /logs/Places_LT
  num_classes: 365
  num_epochs: 20
  num_workers: 8
  open_threshold: 0.1
  sampler: null
  scheduler_params: {gamma: 0.1, step_size: 30}
  stage: ViTB_16_Places_LT
  sub_dir: models
  num_dir: ./data/Places_LT/num_shots.npz
  gamma: 1
  warmup_epoch: 5
  step1: 50
  step2: 70
  base_weight: 2
  bins: 8
